cifarData = {6,2};
load ../cifar-MATLAB/data_batch_1.mat;
cifarData{1,1} = data;
cifarData{1,2} = labels;
load ../cifar-MATLAB/data_batch_2.mat;
cifarData{2,1} = data;
cifarData{2,2} = labels;
load ../cifar-MATLAB/data_batch_3.mat;
cifarData{3,1} = data;
cifarData{3,2} = labels;
load ../cifar-MATLAB/data_batch_4.mat;
cifarData{4,1} = data;
cifarData{4,2} = labels;
load ../cifar-MATLAB/data_batch_5.mat;
cifarData{5,1} = data;
cifarData{5,2} = labels;
load ../cifar-MATLAB/test_batch.mat;
cifarData{6,1} = data;
cifarData{6,2} = labels;
clearvars -except cifarData;